/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  musicTheory:[
    "musicTheory/musicTheory-intro",
    {
      type:"category",
      label:"基础篇", 
      link:{
        type:"generated-index",
        description:"学习乐理知识"
      },
      items:[
        {
          type:"autogenerated",
          dirName:"musicTheory/basics"
        }
      ]
    }
  ],
  languages:[
    "languages/languages-intro",
    {
      type:"category",
      label:"日语",
      link:{
        type:"generated-index",
        description:"自然语言"
      },
      items:[
        {
          type:"autogenerated",
          dirName:"languages/japanese"
        }
      ]
    }
  ],
  design:[
    "design/design-intro",
    {
      type:"category",
      label:"web design",
      link:{
        description:"关于 web 的设计",
        type:"generated-index"
      },
      items:[
        {
          type:"autogenerated",
          dirName:"design/web"
        }
      ]
    }
  ],
  web:[
    "web/intro",
    //ui
    {
      type:"category",
      label:"用户界面",
      link:{
        description:"用于构建网站用户界面的框架或库",
        type:"generated-index"
      },
      items:[
        {
          type:"autogenerated",
          dirName:"web/ui"
        }
      ]
    },

  ],
  algorithm:[
    "algorithm/algorithm-intro",
    {
      type:"category",
      label:"数组 (array)",
      link:{
        description:"作为列表的一种实现方式，数组具有索引，且物理和逻辑上的存储位置都是连续的",
        type:"generated-index"
      },
      items:[
        {
          type:"autogenerated",
          dirName:"algorithm/array"
        }
      ]
    },
    {
      type:"category",
      label:"代数 (algebra)",
      link:{
        description:"数学-代数",
        type:"generated-index"
      },
      items:[
        {
          type:"autogenerated",
          dirName:"algorithm/algebra"
        }
      ]
    }
  ]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
